#!/bin/zsh

# Clear the screen
clear

# Display ASCII art
cat << 'EOF'
   ___                   _         _        _   _               _ ____
  / __|___ _ _  ___  ___| |_    __| |___ __| |_| |_ ___ _ __   (_)__ /
 | (_ / -_) ' \/ _ \/ _ \  _|  / _` / -_|_-< / /  _/ _ \ '_ \   _ |_ \
  \___\___|_||_\___/\___/\__|  \__,_\___/__/_\_\\__\___/ .__/  (_)___/
                                                       |_|
EOF

# Quotes
quotes=("Welcome dani to le epic puter :fire:"
        "I forgor :<"
        "Quote unavaible because uhhh uhmm idk it just skipped work today"
        "I love Rei i love my hubby i love my hubbyy awawaw :3"
        "Who up emerging -avuDU'ing @world"
        "Aawawaw,,aw,aw,wa bwabwaaa bwaa!!! :3"
        "The fog is coming the fog is coming the fog is coming the fo-"
        "Some DMs SUCKS, but the daniDM SUCKS less"
        "Don't forget to take your E today, dani :3"
        "Who's joe"
        "Rei just told me to add 'fuck potemkin' to the random quotes list so uhh yeah now this is here :3 (i love my hubby)"
        "Dnai genoot desktop gaming"
        "Have a nice day, dani :3"
        "Imaginem tipo um gajo que chega ao restaurante e diz 'queria um bitoque' e o empregado responde 'querias batatinhas com enguias' e o gajo responde 'por acaso não mas agora que fala nisso pode trazer haha' e o empregado diz 'não há mesmo batatinhas com enguias ra só uma piada' e o gajo diz 'ah está bem'"
        "Larry loves (Gentoo) Linux! :3"
        "ltaam zuumraa rašuubti ilatim, liittaiid beleet niši rabiit Igigi, Ištár zuumra rašuubti ilatim liittaiid, beleet išii rabiit Igigi."
        "Hello my name dnai,,, welcom tu da genoot desktop,, haii :3")

random_quote=${quotes[$((RANDOM % ${#quotes[@]}))]}

# Greeter message
echo
echo "Haiii Dani (me!!) :3"
echo "Today is: $(date)"
echo "Kernel version: $(uname -r)"
echo -e "Funi quote of the day :3 : ${random_quote}${reset}"
echo
echo "Press 1 to launch river."

# Read user input
read -r login

# Check the user choice and execute the corresponding command
case "$login" in
  1)
    echo "Launching river..."
    exec dbus-launch river
    ;;
  *)
    echo "Invalid choice, exiting..."
    exit 1
    ;;
esac